### PR TITLE
Fix unknown flag sdf-filter

### PR DESCRIPTION
**Pull request by abousselmi**

### CODE REVIEW

**Comment by gab-arrobo** [comment]
@abousselmi please sign the CLA and also rebase your PR. Thanks!

**Comment by abousselmi** [comment]
Hi @gab-arrobo I tried many times on https://cla.opennetworking.org/ but I've never got an email to validate the CLA

**Comment by gab-arrobo** [comment]
> Hi @gab-arrobo I tried many times on https://cla.opennetworking.org/ but I've never got an email to validate the CLA

Hi @dafATonf, can you please help @abousselmi address the issue with the CLA?

**Comment by gab-arrobo** [comment]
@abousselmi, can you please give it a try to sing the CLA one more time? Thanks!

**Pull request closed without merging**
